### ISSUE TITLE
Pip has an older vrsion

### ISSUE THREAD

**Issue by Jokinen** [edoburu/django-fluent-comments#48]
Pip has the version 0.9.2 which has a few issues with newer Django releases. I used some time researching fixes for these out of my own stupidity. Regardless I humbly request that you'd add some info of this near the pip install instructions.

I only noticed that the fixes were present in GitHub after coming to report them.

**Comment by vdboor** [comment]
A django-fluent-comments 1.0 release has just been uploaded to PyPI
