### ISSUE TITLE
missing a comma between .js-comments-form-orig-position .comment-cancel-reply-link

### ISSUE THREAD

**Issue by bung87** [edoburu/django-fluent-comments#49]
.js-comments-form-orig-position .comment-cancel-reply-link {
  display: none;
}
should be .js-comments-form-orig-position, .comment-cancel-reply-link

**Comment by vdboor** [comment]
Nope, this is on purpose. The cancel reply link should only appear when you reply to a threaded comment. The cancel link restores the form in the original position.
