### ISSUE TITLE
get_query_set method should be renamed get_queryset

### ISSUE THREAD

**Issue by philippeluickx** [edoburu/django-fluent-comments#52]
Warning on running server:

site-packages/django/forms/widgets.py:143: RemovedInDjango18Warning: `FluentCommentsAdmin.queryset` method should be renamed `get_queryset`.
  .__new__(mcs, name, bases, attrs))

site-packages/django/forms/widgets.py:143: RemovedInDjango18Warning: `FluentCommentsAdmin.queryset` method should be renamed `get_queryset`.
  .__new__(mcs, name, bases, attrs))

**Comment by vdboor** [comment]
Closing since #53 got merged!
