### ISSUE TITLE
Custom model

### ISSUE THREAD

**Issue by marcelkornblum** [edoburu/django-fluent-comments#55]
Is it possible to extend the FluentComment model, or the underlying Comment model at all? I have a system where I would like comments to be votable and I would like to use a mixin on the Comment model - but keep everything else about this app. Is this possible without a fork/custom install?

**Comment by vdboor** [comment]
Yes, definitely! You can extend it, or just extend the Comment model. If you look at the code, you'll see that the `FluentComment` model is just a proxy that installs a different manager - only to make sure the admin works more efficiently.

**Comment by Sheepzez** [comment]
@vdboor How would I make Fluent Comments use my custom form? I'm using fluent comments with threaded comments in Django 1.9. I want to add two checkboxes in my comment form, and perform custom logic based on those two checkboxes. 

I've created a new form inheriting from FluentCommentForm as follows:

```
from fluent_comments import FluentCommentForm
from django import forms

class NotifyCommentForm(FluentCommentForm):
    notifyNewsletter = forms.BooleanField(required=False)
    notifyReply = forms.BooleanField(required=False)
```

How would I get this form to be used in Crispy?

**Comment by fproldan** [comment]
@vdboor Hi! can you give me an example of how can i extend the Comment model? I need to add a ImageField. Thanks!
